version: '3.8'

services:
  app:
    build: .
    container_name: profile_api_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/profiles?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo_data: